// •	Industryleri 'Energy' olan tum Accountlarin opportunitylerini getirip data table ile gosterme ve bu opportunitylerin Amount toplamlarini screen ekran ile gosterme..
//1.Aşama : Soql Accountlar gelecek filtrelenmiş olarak
//2.Aşama : Datatable bu Accountları istediğimiz fieldlar ile beraber tablo olarak gösterme
//3.Aşama : Accountlardan birinin tablo üzerinden seçilmesi...
//4.Aşama: Seçilen Accounta bağlı opportunityler tabloda gösterilecek
//5.Aşama: Amount toplamlarını içinde tutacak bir variable create ediyoruz.
//6.Aşama : Opportunityleri for döngüsüne koyacağız
//7.Aşama : Her Opportunitynin amountunu total amounta ekleyeceğiz.
//8.Aşama : Total Amountu yazdıracağız